version: '3.7'

services:
  db:
    image: postgres:15
    container_name: postgres_database
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.50'
          memory: 64M 

  redis:
    image: redis:7
    container_name: redis_database
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.50'
          memory: 128M 
