version: '3.7'
services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis

  app: 
    build: 
      context: .
    container_name: fastapi
    env_file:
      - .env-non-dev
    command: ['/fastapi/docker/app.sh']
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis