"""message timezone

Revision ID: 9d740d0c91cd
Revises: 65d3d54a9e59
Create Date: 2023-05-08 13:11:43.178757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d740d0c91cd'
down_revision = '65d3d54a9e59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
